services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  app:
    build: .
    ports:
      - "8081:8000"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
      - DOCKER_ENV=true
      - API_KEY=${API_KEY}
      - CORS_ORIGINS=*
      # File injection configuration temporarily disabled for API key testing
      # - INJECTED_FILE_PATH=/app/injected-config.json
      # - INJECTED_FILE_CONTENT=ewogICJleGFtcGxlIjogInRydWUiLAogICJjb25maWciOiB7CiAgICAic2V0dGluZyI6ICJ2YWx1ZSIKICB9Cn0=
    env_file:
      - .env
    # Removed volume mount to enforce Docker-only execution

  worker:
    build: .
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
      - DOCKER_ENV=true
      - API_KEY=${API_KEY}
      - CORS_ORIGINS=*
      # File injection configuration temporarily disabled for API key testing
      # - INJECTED_FILE_PATH=/app/injected-config.json
      # - INJECTED_FILE_CONTENT=ewogICJleGFtcGxlIjogInRydWUiLAogICJjb25maWciOiB7CiAgICAic2V0dGluZyI6ICJ2YWx1ZSIKICB9Cn0=
    env_file:
      - .env
    # Removed volume mount to enforce Docker-only execution
    command: ["/usr/local/bin/startup.sh", "worker"]

volumes:
  redis_data: